export const SESSION_SECTIONS = [
  'CURRENT TREATMENT GOAL/FOCUS OF SESSION',
  'CHANGES TO MEDICAL, BEHAVIORAL, OR PSYCHIATRIC STATUS SINCE LAST APPOINTMENT',
  'SPECIFIC INTERVENTIONS AND STRUCTURED ACTIVITIES',
  'CONSUMER RESPONSE TO INTERVENTIONS',
  'TREATMENT PROGRESS OR LACK OF PROGRESS',
  'FOLLOW-UP PLAN/TREATMENT SCHEDULE'
] as const;

export const ASSESSMENT_SECTIONS = [
  'CLIENT INFORMATION',
  'PRESENTING PROBLEM',
  'MENTAL STATUS & CLINICAL OBSERVATIONS',
  'ASSESSMENT RESULTS',
  'CLINICAL HISTORY',
  'RISK ASSESSMENT',
  'CLINICAL IMPRESSION',
  'STRENGTHS AND CHALLENGES',
  'TREATMENT RECOMMENDATIONS'
] as const;

export const REQUIRED_ACRONYMS = {
  TH: 'Therapist',
  CL: 'Client'
};

export const MAX_SENTENCES_PER_SECTION = 10;
export const MIN_SENTENCES_PER_SECTION = 5;

export const SENTENCE_ENDINGS = /[.!?]+(?=\s+|$)/;